// supabase/functions/send-push/index.ts
//
// Ate — PUSH for "ate with" (0058/0059). Woken by the database (pg_net, from push_kick: on a tag of a
// sorted entry, on an entry finishing its sort with pending tags, and every minute by pg_cron while
// anything is ready). It drains: claims ready notifications, sends each to the recipient's devices
// over APNs, marks them pushed, drops dead tokens.
//
//   POST /functions/v1/send-push      Authorization: Bearer <kick secret | service role key>   body: ignored
//   → 200 { ok, claimed, sent, marked, dropped }
//     200 { ok: true, configured: false }   (any APNS_* secret absent — claims nothing, a harmless no-op)
//     401 unauthorized · 500 claim failed, or { ok: false, …, errors } when a mark/drop/send failed —
//     rows are settled one by one as their sends return, so a failure never leaves a sent row unmarked.
//   The kick secret is generated by the database (0059 push_configure) and read here once through the
//   service-role client (push_kick_secret()); nobody copies the service-role key. verify_jwt = false
//   (config.toml): the kick secret is not a JWT, so this function checks its own bearer.
//
// WHAT IS SENT is decided in SQL (push_claim_ate_with, 0059): pending tag, unread, undismissed, unpushed
// (so never a quiet re-tag), no block, the tagger's entry sorted. This file never widens that set.
//
// APNs: HTTP/2 (Deno's fetch negotiates h2 by ALPN) with token auth — an ES256 JWT from the .p8 key,
// cached under 50 minutes. Secrets: APNS_KEY_ID, APNS_TEAM_ID, APNS_PRIVATE_KEY (the .p8's PEM text).
// The host is chosen PER TOKEN from device_push_tokens.apns_env (sandbox → api.sandbox.push.apple.com,
// production → api.push.apple.com): a TestFlight build on staging holds a production token. One key
// serves both hosts. Topic com.eamongracias.ate. Payload: push.ts `payload()`; contract in integration-design.md.

import { createClient } from 'npm:@supabase/supabase-js@2';
import { createHandler, type Db } from './push.ts';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

Deno.serve(createHandler({
  env: (name) => Deno.env.get(name),
  db: () => createClient(SUPABASE_URL, SERVICE_ROLE, { auth: { persistSession: false } }) as unknown as Db,
  fetch: (url, init) => fetch(url, init),
}));
